{% set name = "pointpats" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eedb30a17e59746ed9ac68283f419dee5a07c17cd53ed2bc2dadba2b77973ff

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools >=61.0
    - wheel
  run:
    - python
    - scipy >=1.10
    - numpy >=1.24
    - pandas >=1.4,!=1.5.0
    - matplotlib-base >=3.6
    - libpysal >=4.8
    - geopandas >=0.12
    - shapely >=2

test:
  source_files:
    - pointpats
  imports:
    - pointpats
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv pointpats/tests


about:
  home: https://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Statistical analysis of planar point patterns.

  description: |
    This pointpats package is intended to support the statistical analysis
    of planar point patterns.
  doc_url: https://pysal.org/pointpats/
  dev_url: https://github.com/pysal/pointpats

extra:
  recipe-maintainers:
    - weikang9009
    - slumnitz
